[package]
name = "miniquad-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitmask-enum = "2.1.0"
cfg-if = "1"
bytemuck = { version = "1.12", features = ["derive"] }
glam = { version = "0.23.0", features = ["scalar-math"] }
miniquad = "0.3.15"
pollster = "0.2"
inflate = "0.4"
byteorder = "1.4"
asefile = { version = "0.3", features = ["utils"] }
notify = "5.1.0"
rand = "0.8.5"
fontdue="0.7"
tobj = "3.2"
msdfgen = "0.2.1"
# msdf = "0.2"
# freetype-rs = "0.32.0"
ttf-parser = "0.18"
# ttf-parser = "0.15"
# mint = "0.5"


[dependencies.image]
version = "0.23.1"
default-features = false
features = ["png", "jpeg", "tga"]

[dependencies.getrandom]
features = ["js"]

[dev-dependencies]

[profile.dev.package.asefile]
opt-level = 2  # or 3
